apiVersion: v1
kind: Service
metadata:
  name: thumbor
spec:
  selector:
    fint.service: thumbor
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\bin\kompose.exe convert --deployment -f .\docker-stack-beta.yml
      --suppress-warnings
    kompose.version: 1.18.0 (06a2e56)
  labels:
    fint.service: thumbor
  name: thumbor
spec:
  replicas: 3
  strategy: 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  selector:
    matchLabels:
      fint.service: thumbor
  template:
    metadata:
      labels:
        fint.service: thumbor
    spec:
      restartPolicy: Always
      volumes:
        - name: cache
          emptyDir: {}
      containers:
      - name: thumbor
        image: fintlabs.azurecr.io/thumbor:6.5.2-2
        ports:
          - containerPort: 8888
        readinessProbe:
          httpGet:
            port: 8888
            path: /healthcheck
        env:
        - name: TZ
          value: Europe/Oslo
        resources: 
          limits:
            cpu: "2"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        volumeMounts:
          - name: cache
            mountPath: /tmp/thumbor/storage
